import { VoicePreset, VoicePresetKey } from "../types";

export const VOICE_PRESETS: Record<VoicePresetKey, VoicePreset> = {
  normal: {
    label: "Normal (No FX)",
    filterType: "allpass",
    filterFrequency: 1200,
    filterQ: 1,
    filterGain: 0,
    outputGain: 1,
    playbackRate: 1,
  },
  custom: {
    label: "Custom (Manual)",
    filterType: "allpass",
    filterFrequency: 1200,
    filterQ: 1,
    filterGain: 0,
    outputGain: 1,
    playbackRate: 1,
  },
  squirrel: {
    label: "Squirrel Voice",
    filterType: "allpass",
    filterFrequency: 1200,
    filterQ: 1,
    filterGain: 0,
    outputGain: 1,
    playbackRate: 1.4,
  },
  batman: {
    label: "Batman",
    filterType: "lowpass",
    filterFrequency: 520,
    filterQ: 1.4,
    filterGain: 5,
    outputGain: 1.1,
    playbackRate: 0.7,
  },
  robot: {
    label: "Robot",
    filterType: "bandpass",
    filterFrequency: 780,
    filterQ: 10,
    filterGain: 10,
    outputGain: 0.95,
    playbackRate: 1,
  },
  telephone: {
    label: "Telephone",
    filterType: "bandpass",
    filterFrequency: 1500,
    filterQ: 3.2,
    filterGain: -2,
    outputGain: 1,
    playbackRate: 1,
  },
  megaphone: {
    label: "Alien",
    filterType: "bandpass",
    filterFrequency: 1550,
    filterQ: 8.5,
    filterGain: 6,
    outputGain: 1.22,
    playbackRate: 1.18,
  },
};
